### ISSUE TITLE
First Added Stash Items Not Appearing For Game Editions With Default "Rotated" Stash Items

### ISSUE THREAD

**Issue by RogueTech67** [SkiTles55/SPT-AKI-Profile-Editor#18]
**Versions**
- SPT-AKI Server version: SPT-AKI 2.3.1
- SPT-AKI Profile Editor version:  2.1.1 for SPT-AKI server 2.2.0 - 2.3.1
- List of installed mods: NONE

For me, there is an issue with adding the first items to the stash in 2 of the 4 "Default/New Profile" game editions.  It appears the user profile.json is has "invalid" or "unhandled" values in it causing the Profile Editor to add items to blocks in the Stash that it thinks are "free" but are actually used.
For me, when the [Standard] edition was chosen and the user profile created, there were items created in the Stash in their "not normal position/direction".  It was 2 of the [Car first aid kit]'s.  So they took up 2 squares up/down vertically instead of left/right.  Thus in the user profile.json it was listed "incorrecly" with a "location": "r": value of (1) instead of (0).  So when you use the Profile Editor and add say all 6 maps, when the game loads, in the Stash you ONLY see 4 of them.  The other 2 are "hidden" behind in the 2 lower squares of the [Car first aid kit]'s because the Profile Editor assumed those squares/blocks/slots were open.  This is evident by "moving them, closing the game, and once restarted you will then see the other 2 "missing" maps.  Once you "move" and repostion them, they "correctly" get changed in the profile.json with "location": "r": value of "Vertical", meaning "rotated" position/direction, NOT the direction.  After moving an item in the Stash "r": "Horizonal" means "normal" position/direction, and "Vertical" means "rotated".  When items get "initially" put in the stash by purchasing them, they get entered in the profile.json with a location "r": 0 value.  Then once repostioned by the user, they get tagged as either "Horizonal" or "Vertical".
    Since the default beginning [Car first aid kit]'s were created in the stash in their "rotated" position, they got initially added as "r": 1 instead of 0.  For me, this "issue" happen with the [Standard] and [Edge of Darkness] editions ONLY.  The [Standard] edition has (2) rotated items with (2) hidden blocks, and the [Edge of Darkness] edition has (4) rotated items with (5) hidden blocks  The [Left Behind] and [Prepare to Escape] editions did not have any default "rotated" items, thus did not have an issue with adding items via the Profile Editor.
     Also, maybe the user profile.json should have "location": value "r": 1, for items added to the Stash that are "rotated", and the [Profile Editor] is simply not recognizing and handling that situation properly. I went back and checked version 0.12.12.15.17107 (11 Mar 2022) *** add SPT-AKI 2.3.0, and the same exact conditions apply.  The user profile.json is being initially created with any "rotated" items having the "r": 1, value and the Profile Editor is not recognizing this when determining free blocks available when "Adding Stash Items".  I hope I was able to explain this well enough.   Thanks.

Example: .json
"slotId": "hideout",
            "location": {
              "x": 8,
              "y": 16,
              "r": 1,
[Standard]
- First new items added to end of stash
- 2 MISSING
** MISSING ** under [Car first aid kit]
** MISSING ** under [Car first aid kit]

[Edge of Darkness]
- First new items added to the end of stash
- *** 5 MISSING
** MISSING ** under [5.56x45 Colt AR-15 STANAG 30-round magazine]
** MISSING ** under [Kiba Arms Tactical Tomahawk]
** MISSING ** under [Kiba Arms Tactical Tomahawk]
** MISSING ** under [5.56x45 Colt AR-15 STANAG 30-round magazine]
** MISSING ** under [Car first aid kit]

**Additional context**
SPT-AKI Profile file link

**Comment by SkiTles55** [comment]
Thank you for reporting, and your work about figuring out issue. Thats helps a lot. Issue fixed with 288166fadbe87fe939fbcdd5b33d65b3730c3b7f

**Comment by RogueTech67** [comment]
Glad I could help.  Any idea when it will be released/updated?   It just popped up/refreshed on the sp-tarkov site ( https://hub.sp-tarkov.com/files/file/133-spt-aki-profile-editor/ ) under the [Recent Updates] from 20 hours ago, but it is still the same 2.1.1 (Apr 9, 2022) version I had downloaded weeks ago.   Thanks

**Comment by SkiTles55** [comment]
@RogueTech67 So far, there are no plans to release a new version. When the release is released, the program will show at startup that an update is available.

**Comment by RogueTech67** [comment]
Perfect, thanks.  Really appreciate the support.......

**Comment by RogueTech67** [comment]
[SkiTles55], I see new version 2.2 is out.  I verified that this issue has been fixed.  Now, initially adding all 6 maps, shows all 6 maps in the stash of all 4 Game Versions.   Thanks again.
